FROM node:22-bookworm-slim

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY tsconfig.json ./
COPY lambdas ./lambdas
COPY local ./local

EXPOSE 9999

CMD ["pnpm", "tsx", "local/userApiServer.ts"]
