name = "link-auth-account"
main = "src/index.ts"
compatibility_date = "2026-04-26"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "link-auth-assets"

[[d1_databases]]
binding = "DB"
database_name = "link-auth"
database_id = "bf3d55a3-44f8-47c8-a333-675851b88819"
preview_database_id = "DB"
migrations_dir = "migrations"
