name = "org-auth-account"
main = "src/index.ts"
compatibility_date = "2026-04-26"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "org-auth-assets"

[[d1_databases]]
binding = "DB"
database_name = "org-auth"
database_id = "00000000-0000-0000-0000-000000000000"
preview_database_id = "DB"
migrations_dir = "migrations"
